name = "GPLinearODEMaker"
uuid = "27ef9b34-1325-4cec-ba33-00f2f4637873"
authors = ["Chistian Gilbertson <chistianjgilbertson@gmail.com>"]
version = "0.1.12"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"

[compat]
IterativeSolvers = "0.8, 0.9"
SpecialFunctions = "0.10.0, 1.0, 2"
SymEngine = "0.8"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
